name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17.2

      - run: go install github.com/mitchellh/gox@v1.0.2-0.20210311182516-8c3b2b9e647d

      - name: get release version
        id: get_version
        run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@v2

      - run: echo $(go env GOPATH)/bin >> $GITHUB_PATH

      - run: make release
        env:
          RELEASE: ${{ steps.get_version.outputs.RELEASE_TAG }}

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "pkg/*"
          allowUpdates: true
          omitBody: true
          prerelease: true
          removeArtifacts: true
