name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - run: go install github.com/mitchellh/gox@v1.0.2-0.20210311182516-8c3b2b9e647d
      - run: echo $(go env GOPATH)/bin >> $GITHUB_PATH

      - name: get release version
        id: get_version
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/tags/v}

      - uses: actions/checkout@v3

      - run: make release
        env:
          RELEASE: ${{ steps.get_version.outputs.RELEASE_VERSION }}

      - run: openssl dgst -sha256 pkg/*

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "pkg/*"
          allowUpdates: true
          omitBody: true
          prerelease: true
          removeArtifacts: true
